name: PLD Agile

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          mkdir .venv
          python -m pip install pipenv
          pipenv install --dev
      - name: Run lint
        run: |
          .venv/bin/python -m black --check src/
          .venv/bin/python -m isort --check src/

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          mkdir .venv
          python -m pip install pipenv
          pipenv install --dev
      - name: Run tests
        run: .venv/bin/python -m pytest src/

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          mkdir .venv
          python -m pip install pipenv
          pipenv install --dev
      - name: Build
        run: |
          .venv/bin/python -m pyinstaller --windowed --name "PLD Agile" --paths "." src/pld_agile/main.py
          ls dist